# Generated by Django 4.1.7 on 2023-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=255)),
                ('absence', models.IntegerField()),
                ('justifier', models.IntegerField()),
                ('non_justifier', models.IntegerField()),
                ('justification', models.CharField(max_length=255)),
            ],
        ),
    ]
